### ISSUE TITLE
Fix word model file for rmy-rlo, and add language code mapping

### ISSUE THREAD

**Issue by pierrebeauguitte** [giellalt/CorpusTools#5]
The language model file [rm-rlo.wm](https://github.com/giellalt/CorpusTools/blob/main/corpustools/lm/rm-rlo.wm) should be renamed to `rmy-rlo.wm` to follow file naming convention. Currently the file is ignored when creating a `Classifier` in [text_cat.py](https://github.com/giellalt/CorpusTools/blob/main/corpustools/text_cat.py).

A good number (19) of the language models in the `lm/` directory use language codes that are not defined in ISO 639-2. I looked for the codes in the repository and on https://giellalt.github.io/, but haven't been able to find them. Could you document their signification?

**Comment by albbas** [comment]
We use ISO 639-3 as language codes for internal use. If needed, we [convert](https://github.com/giellalt/giella-core/blob/main/scripts/iso3-to-2.sh) them to ISO 639-2 when that is needed and applicable.

They are fetched from https://iso639-3.sil.org/code_tables/download_tables. We have a copy of that in our repo [giella-core](https://github.com/giellalt/giella-core/blob/main/scripts/iso-639-3_20140320.tab.txt).

The -rlo suffix was added by @Trondtr because the `rmy`-code was too unprecise, I'll ask him to add a separate comment on that.

**Comment by pierrebeauguitte** [comment]
@albbas Thank you for the fix and for your answer!

**Comment by Trondtr** [comment]
The `rm-rlo.wm` is a typo, I intended it to be `rmy-rlo.wm` as you correctly point out. Thus, just rename it.

As for the more principled, issue, the code `rlo` (and its twin `rka`) for Lovari and Kalderash are totally ad hoc. What is intended is:
rmy = Vlax Romani (correct ISO code)

Lovari and Kalderash version of Vlach Romani I set as rmy-rlo and rmy-rka, better would perhaps be rmy-x-Lovari and rmy-x-Kalderash (the Glottolog codes are lova1240 and kald1238, respectively). I have got the understanding that -x-XXX (where XXX is some private subgrouping) is a common way of extending codes. At least it is transparent. Be that as it may, if the -rlo and -rka affixes work for the moment we should perhaps wait for more general makeovers to change things. The Right Thing To Do is of course to file an addition to ISO 639-3, there are procedures for that (the reference to 629-2 is irrelevant).
